### PR TITLE
feat(backend,mail-templates): Add Nunjucks include support #38

### PR DESCRIPTION
**Pull request by abordin-spacefill**
Add Nunjucks include support, with an example about how to use it, in .mjml and .txt templates.

### CODE REVIEW

**Comment by Its-Alex** [comment]
@abordin-spacefill Please feel free to open a PR directly from Spacefill repository next time :pray:

**Comment by Its-Alex** [comment]
@abordin-spacefill Can you add some tests in https://github.com/spacefill/gibbon-mail/tree/master/backend/test to check that nunjuck import work?

**Comment by Its-Alex** [comment]
@abordin-spacefill Please can you bump version to `0.5.0` following https://github.com/spacefill/gibbon-mail#how-to-publish-a-tag in another commit? (Be wary to just bump version and not create a tag)

**Comment by Its-Alex** [comment]
@abordin-spacefill I checked the code and it's working perfectly thanks you! :pray:

**Comment by Its-Alex** [comment]
@abordin-spacefill I have one problem on this MR it's that the template are not auto reloading on refresh, for example if I change a template and reload frontends I have no modifications. Before your PR that was working 😅

**Comment by abordin-spacefill** [comment]
@Its-Alex PR updated, all points should be ok now.

**Review by Its-Alex — APPROVED** [review]

**Comment by Its-Alex** [comment]
Closed in favor of https://github.com/spacefill/gibbon-mail/pull/41

**Pull request closed without merging**
